# Generated by Django 5.1.1 on 2024-10-06 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cedula', models.PositiveIntegerField()),
                ('fecha_ingreso', models.DateField()),
                ('puntos', models.IntegerField(default=0)),
                ('referido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.cliente')),
            ],
        ),
    ]
