# Generated by Django 5.1.1 on 2024-10-20 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_cliente_referido_perfil'),
        ('vav', '0002_alter_alquilerventa_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
