# Generated by Django 5.1.1 on 2024-10-20 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sic', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
