# Generated by Django 5.1.1 on 2024-10-06 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('sic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlquilerVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('alquiler', 'Alquiler'), ('venta', 'Venta')], max_length=10)),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True)),
                ('puntos_ganados', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.cliente')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sic.video')),
            ],
        ),
    ]
