# Generated by Django 5.1.1 on 2024-10-20 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vav', '0002_alter_alquilerventa_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISAN', models.CharField(max_length=50, unique=True)),
                ('titulo_original', models.CharField(max_length=255)),
                ('ano', models.IntegerField()),
                ('duracion', models.IntegerField()),
                ('calificacion', models.FloatField(default=0.0)),
                ('clasificacion', models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('NC-17', 'NC-17')], max_length=10)),
                ('idioma_original', models.CharField(max_length=50)),
                ('subtitulos', models.CharField(blank=True, max_length=50)),
                ('doblajes', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='alquilerventa',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vav.video'),
        ),
    ]
