# Generated by Django 5.1.1 on 2024-10-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vav', '0003_video_alter_alquilerventa_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquilerventa',
            name='puntos_ganados',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='ano',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='duracion',
            field=models.PositiveIntegerField(),
        ),
    ]
