# Generated by Django 5.1.1 on 2024-10-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vav', '0007_video_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
